Resolves missing dependencies and duplicate dependencies in the SyncTool. Specifically, ensures that jboss-logging, fasterxml classmate, and commons-beanutils (at the current versions) are included in the SyncTool jar. Also pulls out the httpcore jar from the WEB-INF/lib/ dir of the jar to resolve this error encountered at runtime:
java.lang.LinkageError: loader constraint violation: when resolving interface method "org.apache.http.client.AuthCache.put(Lorg/apache/http/HttpHost;Lorg/apache/http/auth/AuthScheme;)V" the class loader (instance of org/eclipse/jetty/webapp/WebAppClassLoader) of the current class, org/duracloud/common/web/RestHttpHelper, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/apache/http/client/AuthCache, have different Class objects for the type org/apache/http/HttpHost used in the signature